project:
  type: website
  output-dir: docs

  render:
    - index.qmd
    - Install_software.qmd
    - slides/slides_1.qmd
    - practicals/LMM_ex.qmd
website:
  title: "inlabru_NewCaledonia"
  navbar:
    logo: Image/INLA_logo.png
    right:
      - text: "GitHub"
        href: https://github.com/inlabru-courses/NewCaledonia2026   # replace ORG/REPO with your repo URL
        icon: brands/github   # optional: shows GitHub icon
    left:
      - text: "Home"
        href: index.qmd
      - text: "Installation"
        href: Install_software.qmd
      - text: "Slides"
        menu:
          - text: "Slides 1 - Introduction"
            href: slides/slides_1.qmd
      - text: "Practicals"
        menu:
          - text: "Practical 1 - Fit LMM"
            href: practicals/LMM_ex.qmd


format:
  html: {}

execute:
  freeze: auto

